"""empty message

Revision ID: 513a3a176e56
Revises: 9bc1e528e032
Create Date: 2020-05-08 12:17:21.245830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513a3a176e56'
down_revision = '9bc1e528e032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET admin=False')
    op.alter_column('users', 'admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
