"""empty message

Revision ID: 562cdb031a1c
Revises: 
Create Date: 2020-05-06 11:24:02.560771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562cdb031a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
